pipeline {
    agent any
    environment{
        PATH= "/usr/share/maven/bin:$PATH"
    }
    stages {
        stage('SCM Checkout') {
            steps{
               git credentialsId: 'git_credentials', url: 'https://github.com/harishvarma44/Jfrog1.git'
                 }
            }  
        stage('Build') {
            steps {
                // Get maven home path
                //   def mvnHome =  tool name: 'mvn3.3.9', type: 'maven'
                   sh "mvn clean package"
                  }
            }
 
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '.simple-java-maven-app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
